[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = [
  "cd frontend && NODE_ENV=development npm install",
  "cd backend && NODE_ENV=development npm install"
]

[phases.build]
cmds = [
  "cd frontend && VITE_API_URL=/api VITE_SOCKET_URL=/ npm run build",
  "cd backend && npm run build"
]

[start]
cmd = "cd backend && npm start"
